name: wirya_qr_client
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  geolocator: ^13.0.2
  mobile_scanner: ^6.0.6
  http: ^1.3.0
  shared_preferences: ^2.0.15
  flutter_map: ^6.1.0
  permission_handler: ^11.4.0
  firebase_database: ^11.3.4
  cupertino_icons: ^1.0.8
  geocoding: ^3.0.0
  intl: ^0.20.2
  audioplayers: ^6.2.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  wakelock_plus: ^1.2.10
  workmanager: ^0.5.1 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/beep.mp3